// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFz-sVcVbKMQa_Kn93yV2nwCVf0--BOE',
    appId: '1:826882464220:web:ab0ad2f77968baa9879719',
    messagingSenderId: '826882464220',
    projectId: 'todo-firestore-bf862',
    authDomain: 'todo-firestore-bf862.firebaseapp.com',
    databaseURL: 'https://todo-firestore-bf862-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firestore-bf862.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOBHqp0Vf3UCvwWkEnb4IDYUjmS9LjJE',
    appId: '1:826882464220:android:44500b7875609cee879719',
    messagingSenderId: '826882464220',
    projectId: 'todo-firestore-bf862',
    databaseURL: 'https://todo-firestore-bf862-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firestore-bf862.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqFtbY2SUhcjp9p6HQvSI6cTKQa9sBet0',
    appId: '1:826882464220:ios:b8bc53f98c2a56d9879719',
    messagingSenderId: '826882464220',
    projectId: 'todo-firestore-bf862',
    databaseURL: 'https://todo-firestore-bf862-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firestore-bf862.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqFtbY2SUhcjp9p6HQvSI6cTKQa9sBet0',
    appId: '1:826882464220:ios:3002de05e769c5b7879719',
    messagingSenderId: '826882464220',
    projectId: 'todo-firestore-bf862',
    databaseURL: 'https://todo-firestore-bf862-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firestore-bf862.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
